### ISSUE TITLE
監訳完了から指摘箇所修正のプルリクについて

### ISSUE THREAD

**Issue by mitsuruog** [html5j-english/webplatform#10]
こちらに記載があると思いますが、認識正しいか確認させてください。

https://github.com/html5j-english/README/wiki/Review-and-Pull-Request-Work-Flow

監訳完了時は監訳依頼時のプルリクをクローズして、監訳の指摘箇所を修正したものを新たにプルリクする形でよろしいでしょうか？

**Comment by studiomohawk** [comment]
はい。
某en.ja OSSと違うのですが、
Pull Requestを受け入れるのは監訳後に修正いただいたものとさせていただこうかと。

**Comment by mitsuruog** [comment]
承知しました！
