### ISSUE TITLE
HTML5 hybrid applications

### ISSUE THREAD

**Issue by ichicolo** [html5j-english/webplatform#9]
http://docs.webplatform.org/wiki/concepts/internet_and_web/About_HTML5_hybrid_applications

英語部での翻訳の始め方・フローをまだ理解していないのですが、ひとまず上記のページから翻訳を始めてみたいと思います。宣言方法は、この場所・この方法で合っていますか？

**Comment by studiomohawk** [comment]
@ichicolo さん。
実は未だ英語部におけるオンラインでのワークフローを整備していないのですが、
Webplatform.org において翻訳可能なレベルになっているドキュメントは、
- http://docs.webplatform.org/wiki/beginners
- http://docs.webplatform.org/wiki/css/properties

の2つとなっております。
上記のカテゴリ内にあるドキュメントに対して翻訳をすすめていただくことを推奨している状態です。

上記の様な、オリジナルドキュメントの状況や、翻訳をすすめるべく対象などを含めて、
オンラインでの翻訳ワークフローの整備については急ぎ進めております。

**Comment by ichicolo** [comment]
@studiomohawk さん。承知しました。フライングでしたね。失礼しました。

では、このIssueは一旦Closedにしまして、beginners内のドキュメントから始めようと思います。

**Comment by studiomohawk** [comment]
@ichicolo 
お手数掛けてもうしわけないです!
